name: artemis
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_svg: ^2.0.1
  go_router: ^6.0.9
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.2.0
  intl: ^0.17.0
  liquid_swipe: ^3.0.0
  lottie: ^2.2.0
  material_dialogs: ^1.1.4
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/
    - assets/animation/
  fonts:
    - family: Folks
      fonts:
        - asset: assets/font/FolksLight.ttf
          weight: 300
        - asset: assets/font/FolksRegular.ttf
          weight: 400
        - asset: assets/font/FolksBold.ttf
          weight: 700
        - asset: assets/font/FolksBlack.ttf
          weight: 800
        - asset: assets/font/FolksHeavy.ttf
          weight: 900

flutter_intl:
  enabled: true
